; Waffle Optimization
expose_php = 0
date.timezone = UTC
apc.enable_cli = 1
session.use_strict_mode = 1
zend.detect_unicode = 0

; YAML Security: Disabled !php/object parsing
; 0 = Disabled (Secure), 1 = Enabled (Danger Zone)
yaml.decode_php = 0

; Opcache (Critical for FrankenPHP Worker mode)
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000
opcache.preload_user = www-data

; Uploads
upload_max_filesize = 16M
post_max_size = 16M
